package edu.tx.utep.ltlgenerator.inputoutput; import instrumentor.InstrumentingCode;

import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class OutputToFile extends LTLInputOutput {
	
	protected static String getDateTime(){InstrumentingCode.saveOrigin();InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","getDateTime().xml","START","11");
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","getDateTime().xml","11","12");		DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","getDateTime().xml","12","13");		Date date = new Date();
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","getDateTime().xml","13","14");InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","getDateTime().xml","14","EXIT");		return dateFormat.format(date).toString();
	}
	
	protected static void outputInitialMessage(String outputFile){InstrumentingCode.saveOrigin();InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","START","17");
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","17","18");		StringBuilder stringBuilder = new StringBuilder();
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","18","19");        stringBuilder.append("*********************************************************************************" + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","19","20");        stringBuilder.append("LTL GENERATOR RUN @ " + getDateTime() + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","20","21");        stringBuilder.append("*********************************************************************************" + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","21","22");        saveResultsToFile(outputFile, stringBuilder.toString());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","22","23");InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInitialMessage(java.lang.String).xml","23","EXIT");	}
	
	protected static void outputInputErrorMessage(String outputFile){InstrumentingCode.saveOrigin();InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","START","25");
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","25","26");		StringBuilder stringBuilder = new StringBuilder();
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","26","27");        stringBuilder.append("-----------------------------------------------------------------" + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","27","28");        stringBuilder.append("ERROR READING INPUT SET " + getDateTime() + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","28","29");        stringBuilder.append("-----------------------------------------------------------------" + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","29","30");        saveResultsToFile(outputFile, stringBuilder.toString());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","30","31");InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputInputErrorMessage(java.lang.String).xml","31","EXIT");	}
	
	protected static void outputLTLFormulaResultSet(String outputFile, String scope, String pattern, String p, String q, String r, String l, String ltlFormula){InstrumentingCode.saveOrigin();InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","START","33");
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","33","34");		StringBuilder stringBuilder = new StringBuilder();
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","34","35");		stringBuilder.append(System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","35","36");		stringBuilder.append("---------------------------------------------------------" + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","36","37");		stringBuilder.append("Scope: " + scope + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","37","38");		stringBuilder.append("Pattern: " + pattern + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","38","39");		if (!p.isEmpty()) {
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","39","40");			stringBuilder.append(p + System.lineSeparator());
		}
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","40","42");		if (!q.isEmpty()) {
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","42","43");			stringBuilder.append(q + System.lineSeparator());
		}
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","43","45");		if (!r.isEmpty()) {
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","45","46");			stringBuilder.append(r + System.lineSeparator());
		}
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","46","48");		if (!l.isEmpty()) {
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","48","49");			stringBuilder.append(l + System.lineSeparator());
		}
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","49","51");		stringBuilder.append(System.lineSeparator() + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","51","52");		stringBuilder.append("LTL Formula:" + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","52","53");		stringBuilder.append(ltlFormula + System.lineSeparator());
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","53","54");		stringBuilder.append("---------------------------------------------------------" + System.lineSeparator());
		
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","54","56");		saveResultsToFile(outputFile, stringBuilder.toString());
		
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","56","58");InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","outputLTLFormulaResultSet(java.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String,Ljava.lang.String).xml","58","EXIT");	}
	
	protected static void saveResultsToFile(String outputFile, String results){InstrumentingCode.saveOrigin();InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","START","60");
	   	 try {
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","60","62");	            FileWriter writer = new FileWriter(outputFile, true);
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","62","63");	            writer.write(results);
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","63","64");	            writer.close();
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","64","65");	        } catch (IOException e) {
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","65","66");	            e.printStackTrace();
	        }
InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","66","68");InstrumentingCode.mark("C:\\Users\\ochoao\\Desktop\\Diss\\FinalWorkspace\\TeamDriver\\T2-XML\\edu\\tx\\utep\\ltlgenerator\\inputoutput\\OutputToFile\\","saveResultsToFile(java.lang.String,Ljava.lang.String).xml","68","EXIT");	   }
}
